# Generated by Django 5.2.8 on 2025-11-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_savedproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
