# Generated by Django 5.2.8 on 2025-11-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_main_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this property available for bookings?'),
        ),
    ]
