# Generated by Django 6.0 on 2026-01-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_property_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Link to property tour video (YouTube/Vimeo)",
                null=True,
            ),
        ),
    ]
