# Generated by Django 6.0 on 2026-01-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_development",
            field=models.BooleanField(
                default=False, help_text="Is this a development project?"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="listing_type",
            field=models.CharField(
                choices=[("sale", "For Sale"), ("rent", "For Rent")],
                default="sale",
                max_length=10,
            ),
        ),
    ]
