# Generated by Django 6.0 on 2026-01-21 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_conversation_message"),
        ("properties", "0006_property_is_development_property_listing_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="properties.property",
            ),
        ),
    ]
