# Generated by Django 5.2.8 on 2026-03-21 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_conversation_lead_lead_priority_lead_score_lead_user_and_more'),
        ('properties', '0008_make_location_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-score', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leadactivity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('contact_form', 'Contact Form'), ('book_viewing', 'Book Viewing'), ('saved_property', 'Saved Property'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('phone', 'Phone Call')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('viewing', 'Viewing Scheduled'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('property_viewing', 'Property Viewing'), ('whatsapp', 'WhatsApp Message'), ('note', 'Note'), ('status_change', 'Status Change')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', False)), fields=('client', 'property'), name='unique_client_property_conversation'),
        ),
        migrations.AddField(
            model_name='leadstatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadstatuslog',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='leads.lead'),
        ),
    ]
