# Generated by Django 5.2.8 on 2026-03-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_auto',
            field=models.BooleanField(default=False, help_text='Auto-generated message from system'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
