# Generated by Django 5.2.8 on 2026-03-22 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('leads', '0005_leadstatuslog_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='leads.lead'),
        ),
    ]
