# Generated by Django 5.2.8 on 2025-11-19 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, spaces, and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 _.-]+$', 'Enter a valid username. Only letters, numbers, spaces, underscores, dots, and hyphens are allowed.')]),
        ),
    ]
