# Generated by Django 6.0 on 2026-01-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userpreferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("agent", "Agent"),
                    ("management", "Management"),
                ],
                default="client",
                max_length=10,
            ),
        ),
    ]
